trial for win

diff --git a/.github/workflows/w-Trial.yml b/.github/workflows/w-Trial.yml
--- a/.github/workflows/w-Trial.yml
+++ b/.github/workflows/w-Trial.yml
@@ -42,192 +42,192 @@ jobs:
         run: bash .github/dependencies/build_tools/github/check_build_trigger.sh
 
   # Build the wheels for Linux, Windows and macOS for Python 3.11 and newer
-  # build_wheels:
-  #   name: Build wheel for cp${{ matrix.python }}-${{ matrix.platform_id }}-${{ matrix.manylinux_image }}
-  #   runs-on: ${{ matrix.os }}
-  #   # needs: check_build_trigger
-  #   # if: needs.check_build_trigger.outputs.build
-
-  #   strategy:
-  #     # Ensure that a wheel builder finishes even if another fails
-  #     fail-fast: false
-  #     matrix:
-  #       include:
-  #         # Window 64 bit
-  #         # Note: windows-2019 is needed for older Python versions:
-  #         # https://github.com/scikit-learn/scikit-learn/issues/22530
-  #         # - os: windows-latest
-  #         #   python: 39
-  #         #   platform_id: win_amd64
-  #         # - os: windows-latest
-  #         #   python: 310
-  #         #   platform_id: win_amd64
-  #         - os: windows-latest
-  #           python: 311
-  #           platform_id: win_amd64
-  #         # - os: windows-latest
-  #         #   python: 312
-  #         #   platform_id: win_amd64
-
-  #         # Linux 64 bit manylinux2014
-  #         # - os: ubuntu-latest
-  #         #   python: 39
-  #         #   platform_id: manylinux_x86_64
-  #         #   manylinux_image: manylinux2014
-
-  #         # NumPy on Python 3.10 only supports 64bit and is only available with manylinux2014
-  #         # - os: ubuntu-latest
-  #         #   python: 310
-  #         #   platform_id: manylinux_x86_64
-  #         #   manylinux_image: manylinux2014
-
-  #         - os: ubuntu-latest
-  #           python: 311
-  #           platform_id: manylinux_x86_64
-  #           manylinux_image: manylinux2014
-  #         # - os: ubuntu-latest
-  #         #   python: 312
-  #         #   platform_id: manylinux_x86_64
-  #         #   manylinux_image: manylinux2014
-
-  #         # MacOS x86_64
-  #         # - os: macos-12
-  #         #   python: 39
-  #         #   platform_id: macosx_x86_64
-  #         # - os: macos-12
-  #         #   python: 310
-  #         #   platform_id: macosx_x86_64
-  #           # - os: macos-12
-  #           #   python: 311
-  #           #   platform_id: macosx_x86_64
-  #         # - os: macos-12
-  #         #   python: 312
-  #         #   platform_id: macosx_x86_64
-
-  #         # MacOS arm64
-  #         # - os: macos-14
-  #         #   python: 39
-  #         #   platform_id: macosx_arm64
-  #         # - os: macos-14
-  #         #   python: 310
-  #         #   platform_id: macosx_arm64
-  #           # - os: macos-14
-  #           #   python: 311
-  #           #   platform_id: macosx_arm64
-  #         # - os: macos-14
-  #         #   python: 312
-  #         #   platform_id: macosx_arm64
-
-  #   steps:
-  #     - name: Checkout PKScreener
-  #       uses: actions/checkout@v3
-
-  #     - name: Setup Python
-  #       uses: actions/setup-python@v5
-  #       with:
-  #         python-version: "3.11" # update once build dependencies are available
-
-  #     - name: Install conda for macos arm64
-  #       if: ${{ matrix.platform_id == 'macosx_arm64' }}
-  #       run: |
-  #         set -ex
-  #         # macos arm64 runners do not have conda installed. Thus we much install conda manually
-  #         EXPECTED_SHA="dd832d8a65a861b5592b2cf1d55f26031f7c1491b30321754443931e7b1e6832"
-  #         MINIFORGE_URL="https://github.com/conda-forge/miniforge/releases/download/23.11.0-0/Mambaforge-23.11.0-0-MacOSX-arm64.sh"
-  #         curl -L --retry 10 $MINIFORGE_URL -o miniforge.sh
-
-  #         # Check SHA
-  #         file_sha=$(shasum -a 256 miniforge.sh | awk '{print $1}')
-  #         if [ "$EXPECTED_SHA" != "$file_sha" ]; then
-  #             echo "SHA values did not match!"
-  #             exit 1
-  #         fi
-
-  #         # Install miniforge
-  #         MINIFORGE_PATH=$HOME/miniforge
-  #         bash ./miniforge.sh -b -p $MINIFORGE_PATH
-  #         echo "$MINIFORGE_PATH/bin" >> $GITHUB_PATH
-  #         echo "CONDA_HOME=$MINIFORGE_PATH" >> $GITHUB_ENV
-
-  #     - name: Set conda environment for non-macos arm64 environments
-  #       if: ${{ matrix.platform_id != 'macosx_arm64' }}
-  #       run: |
-  #         # Non-macos arm64 envrionments already have conda installed
-  #         echo "CONDA_HOME=/usr/local/miniconda" >> $GITHUB_ENV
-
-  #     - name: Build and test wheels
-  #       env:
-  #         # CIBW_PRERELEASE_PYTHONS: ${{ matrix.prerelease }}
-  #         # CIBW_ENVIRONMENT: SKLEARN_SKIP_NETWORK_TESTS=1
-  #         #   SKLEARN_BUILD_PARALLEL=3
-  #         CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
-  #         CIBW_ARCHS: all
-  #         CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux_image }}
-  #         CIBW_MANYLINUX_I686_IMAGE: ${{ matrix.manylinux_image }}
-  #         # Needed on Windows CI to compile with Visual Studio compiler
-  #         # otherwise Meson detects a MINGW64 platform and use MINGW64
-  #         # toolchain
-  #         CIBW_CONFIG_SETTINGS_WINDOWS: "setup-args=--vsenv"
-  #         # CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: bash build_tools/github/repair_windows_wheels.sh {wheel} {dest_dir}
-  #         # CIBW_BEFORE_TEST_WINDOWS: bash build_tools/github/build_minimal_windows_image.sh ${{ matrix.python }}
-  #         # CIBW_TEST_REQUIRES: pytest pandas
-  #         # CIBW_TEST_COMMAND: bash {project}/build_tools/wheels/test_wheels.sh
-  #         # CIBW_TEST_COMMAND_WINDOWS: bash {project}/build_tools/github/test_windows_wheels.sh ${{ matrix.python }}
-  #         CIBW_BUILD_VERBOSITY: 1
-
-  #       run: bash .github/dependencies/build_tools/wheels/build_wheels.sh
-
-  #     - name: Store artifacts
-  #       uses: actions/upload-artifact@v3
-  #       with:
-  #         path: wheelhouse/*.whl
-
   build_wheels:
-    name: Build wheels on ${{ matrix.os }}
+    name: Build wheel for cp${{ matrix.python }}-${{ matrix.platform_id }}-${{ matrix.manylinux_image }}
     runs-on: ${{ matrix.os }}
+    # needs: check_build_trigger
+    # if: needs.check_build_trigger.outputs.build
+
     strategy:
+      # Ensure that a wheel builder finishes even if another fails
+      fail-fast: false
       matrix:
         include:
-          # - os: ubuntu-latest
-          #   cibw_archs: "x86_64"
-          #   python: 311
-          # - os: ubuntu-latest
-          #   cibw_archs: "aarch64"
-          #   python: 311
+          # Window 64 bit
+          # Note: windows-2019 is needed for older Python versions:
+          # https://github.com/scikit-learn/scikit-learn/issues/22530
+          # - os: windows-latest
+          #   python: 39
+          #   platform_id: win_amd64
+          # - os: windows-latest
+          #   python: 310
+          #   platform_id: win_amd64
           - os: windows-latest
-            cibw_archs: "native ARM64"
             python: 311
-          - os: macos-latest
-            cibw_archs: "x86_64 universal2 arm64"
-            python: 311
+            platform_id: win_amd64
+          # - os: windows-latest
+          #   python: 312
+          #   platform_id: win_amd64
+
+          # Linux 64 bit manylinux2014
+          # - os: ubuntu-latest
+          #   python: 39
+          #   platform_id: manylinux_x86_64
+          #   manylinux_image: manylinux2014
+
+          # NumPy on Python 3.10 only supports 64bit and is only available with manylinux2014
+          # - os: ubuntu-latest
+          #   python: 310
+          #   platform_id: manylinux_x86_64
+          #   manylinux_image: manylinux2014
+
+          # - os: ubuntu-latest
+          #   python: 311
+          #   platform_id: manylinux_x86_64
+          #   manylinux_image: manylinux2014
+          # - os: ubuntu-latest
+          #   python: 312
+          #   platform_id: manylinux_x86_64
+          #   manylinux_image: manylinux2014
+
+          # MacOS x86_64
+          # - os: macos-12
+          #   python: 39
+          #   platform_id: macosx_x86_64
+          # - os: macos-12
+          #   python: 310
+          #   platform_id: macosx_x86_64
+            # - os: macos-12
+            #   python: 311
+            #   platform_id: macosx_x86_64
+          # - os: macos-12
+          #   python: 312
+          #   platform_id: macosx_x86_64
+
+          # MacOS arm64
+          # - os: macos-14
+          #   python: 39
+          #   platform_id: macosx_arm64
+          # - os: macos-14
+          #   python: 310
+          #   platform_id: macosx_arm64
+            # - os: macos-14
+            #   python: 311
+            #   platform_id: macosx_arm64
+          # - os: macos-14
+          #   python: 312
+          #   platform_id: macosx_arm64
 
     steps:
-      - name: Set up QEMU
-        if: matrix.cibw_archs == 'aarch64'
-        uses: docker/setup-qemu-action@v2
+      - name: Checkout PKScreener
+        uses: actions/checkout@v3
+
+      - name: Setup Python
+        uses: actions/setup-python@v5
         with:
-          platforms: arm64
-      - uses: actions/checkout@v3
-      - name: Build wheels
-        uses: pypa/cibuildwheel@v2.18.0
+          python-version: "3.11" # update once build dependencies are available
+
+      - name: Install conda for macos arm64
+        if: ${{ matrix.platform_id == 'macosx_arm64' }}
+        run: |
+          set -ex
+          # macos arm64 runners do not have conda installed. Thus we much install conda manually
+          EXPECTED_SHA="dd832d8a65a861b5592b2cf1d55f26031f7c1491b30321754443931e7b1e6832"
+          MINIFORGE_URL="https://github.com/conda-forge/miniforge/releases/download/23.11.0-0/Mambaforge-23.11.0-0-MacOSX-arm64.sh"
+          curl -L --retry 10 $MINIFORGE_URL -o miniforge.sh
+
+          # Check SHA
+          file_sha=$(shasum -a 256 miniforge.sh | awk '{print $1}')
+          if [ "$EXPECTED_SHA" != "$file_sha" ]; then
+              echo "SHA values did not match!"
+              exit 1
+          fi
+
+          # Install miniforge
+          MINIFORGE_PATH=$HOME/miniforge
+          bash ./miniforge.sh -b -p $MINIFORGE_PATH
+          echo "$MINIFORGE_PATH/bin" >> $GITHUB_PATH
+          echo "CONDA_HOME=$MINIFORGE_PATH" >> $GITHUB_ENV
+
+      - name: Set conda environment for non-macos arm64 environments
+        if: ${{ matrix.platform_id != 'macosx_arm64' }}
+        run: |
+          # Non-macos arm64 envrionments already have conda installed
+          echo "CONDA_HOME=/usr/local/miniconda" >> $GITHUB_ENV
+
+      - name: Build and test wheels
         env:
-          CIBW_BUILD: "cp311-*"
-          CIBW_ARCHS: ${{ matrix.cibw_archs }}
-          CIBW_SKIP: "pp*"
-          # CIBW_TEST_REQUIRES: pytest
-          # CIBW_TEST_COMMAND: pytest {package}
-      - name: Build wheels for PyPy
-        uses: pypa/cibuildwheel@v2.18.0
-        env:
-          CIBW_BUILD: "cp311-*"
-          CIBW_ARCHS: ${{ matrix.cibw_archs }}
-        if: matrix.cibw_archs != 'aarch64'
+          # CIBW_PRERELEASE_PYTHONS: ${{ matrix.prerelease }}
+          # CIBW_ENVIRONMENT: SKLEARN_SKIP_NETWORK_TESTS=1
+          #   SKLEARN_BUILD_PARALLEL=3
+          CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
+          CIBW_ARCHS: all
+          # CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux_image }}
+          # CIBW_MANYLINUX_I686_IMAGE: ${{ matrix.manylinux_image }}
+          # Needed on Windows CI to compile with Visual Studio compiler
+          # otherwise Meson detects a MINGW64 platform and use MINGW64
+          # toolchain
+          CIBW_CONFIG_SETTINGS_WINDOWS: "setup-args=--vsenv"
+          # CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: bash build_tools/github/repair_windows_wheels.sh {wheel} {dest_dir}
+          # CIBW_BEFORE_TEST_WINDOWS: bash build_tools/github/build_minimal_windows_image.sh ${{ matrix.python }}
+          # CIBW_TEST_REQUIRES: pytest pandas
+          # CIBW_TEST_COMMAND: bash {project}/build_tools/wheels/test_wheels.sh
+          # CIBW_TEST_COMMAND_WINDOWS: bash {project}/build_tools/github/test_windows_wheels.sh ${{ matrix.python }}
+          CIBW_BUILD_VERBOSITY: 1
+
+        run: bash .github/dependencies/build_tools/wheels/build_wheels.sh
+
+      - name: Store artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          path: wheelhouse/*.whl
+
+  # build_wheels:
+  #   name: Build wheels on ${{ matrix.os }}
+  #   runs-on: ${{ matrix.os }}
+  #   strategy:
+  #     matrix:
+  #       include:
+  #         # - os: ubuntu-latest
+  #         #   cibw_archs: "x86_64"
+  #         #   python: 311
+  #         # - os: ubuntu-latest
+  #         #   cibw_archs: "aarch64"
+  #         #   python: 311
+  #         - os: windows-latest
+  #           cibw_archs: "native ARM64"
+  #           python: 311
+  #         - os: macos-latest
+  #           cibw_archs: "x86_64 universal2 arm64"
+  #           python: 311
+
+  #   steps:
+  #     - name: Set up QEMU
+  #       if: matrix.cibw_archs == 'aarch64'
+  #       uses: docker/setup-qemu-action@v2
+  #       with:
+  #         platforms: arm64
+  #     - uses: actions/checkout@v3
+  #     - name: Build wheels
+  #       uses: pypa/cibuildwheel@v2.18.0
+  #       env:
+  #         CIBW_BUILD: "cp311-*"
+  #         CIBW_ARCHS: ${{ matrix.cibw_archs }}
+  #         CIBW_SKIP: "pp*"
+  #         # CIBW_TEST_REQUIRES: pytest
+  #         # CIBW_TEST_COMMAND: pytest {package}
+  #     - name: Build wheels for PyPy
+  #       uses: pypa/cibuildwheel@v2.18.0
+  #       env:
+  #         CIBW_BUILD: "cp311-*"
+  #         CIBW_ARCHS: ${{ matrix.cibw_archs }}
+  #       if: matrix.cibw_archs != 'aarch64'
   
-      - uses: actions/upload-artifact@v3
-        with:
-          name: wheels
-          path: ./wheelhouse/*.whl
-          if-no-files-found: error
+  #     - uses: actions/upload-artifact@v3
+  #       with:
+  #         name: wheels
+  #         path: ./wheelhouse/*.whl
+  #         if-no-files-found: error
 
   # update-tracker:
   #   uses: ./.github/workflows/update_tracking_issue.yml
